
-- =======================
-- error_list
-- =======================
create table public.error_list (
  id bigint generated by default as identity not null,
  name text not null,
  constraint error_list_pkey primary key (id)
) TABLESPACE pg_default;

-- =======================
-- errors
-- =======================
create table public.errors (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  game_id bigint not null,
  error_id bigint null,
  user_id uuid not null,
  constraint errors_pkey primary key (id),
  constraint errors_error_id_fkey foreign KEY (error_id) references error_list (id),
  constraint errors_game_id_fkey foreign KEY (game_id) references games (id),
  constraint errors_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;


-- =======================
-- games
-- =======================
create table public.games (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  finished_at timestamp with time zone null,
  user_id uuid not null,
  constraint games_pkey primary key (id),
  constraint games_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;